const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../engine.js');
const START=Date.parse('2026-10-09T01:00:00Z');
function rng(seed=7){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t^=t+Math.imul(t^t>>>7,61|t);return ((t^t>>>14)>>>0)/4294967296;};}
function fixture(state=C.fresh(START),seed=7){return new C.Game(state,{now:()=>START,rng:rng(seed)});}
test('chopping consumes peaches, grants experience and produces usable equipment',()=>{const g=fixture(),r=g.chop();assert.equal(g.state.resources.peaches,119);assert.equal(g.state.xp,10);assert.equal(g.state.counts.chops,1);assert.equal(g.state.bag.length,1);const before=C.power(g.stats());g.equip(r.item.id);assert.ok(C.power(g.stats())>before);assert.equal(g.state.bag.length,0);});
test('equipment swaps retain the old equipment without duplicate identities',()=>{const g=fixture();let previous;for(let i=0;i<30;i++){const r=g.chop();if(g.state.equipment[r.item.slot])previous=g.state.equipment[r.item.slot].id;g.equip(r.item.id);}assert.ok(previous);assert.ok(g.state.bag.some(x=>x.id===previous));const all=[...g.state.bag,...Object.values(g.state.equipment)];assert.equal(new Set(all.map(i=>i.id)).size,all.length);});
test('automatic chopping resolves equipment and never fills the bag with junk',()=>{const s=C.fresh(START);s.resources.peaches=300;const g=fixture(s);for(let i=0;i<200;i++)g.chop(true);assert.equal(g.state.bag.length,0);assert.equal(Object.keys(g.state.equipment).length,8);assert.ok(g.state.resources.gold>600);assert.equal(g.state.resources.peaches,100);});
test('manual inventory overflow is converted to resources without losing newer items',()=>{const s=C.fresh(START);s.resources.peaches=100;const g=fixture(s);for(let i=0;i<90;i++)g.chop();assert.equal(g.state.bag.length,80);assert.equal(g.state.bag[0].id,'item-11');assert.ok(g.state.resources.gold>600);});
test('failed purchases and attempts to chop without peaches preserve the resources',()=>{const s=C.fresh(START);s.resources.peaches=0;s.resources.gems=0;const g=fixture(s);const before=JSON.stringify(g.state.resources);assert.throws(()=>g.chop(),/仙桃不足/);assert.throws(()=>g.buy('eggs'),/仙玉不足/);assert.equal(JSON.stringify(g.state.resources),before);assert.equal(g.state.nextItem,1);});
test('mission and daily rewards can each be claimed only once',()=>{const g=fixture();for(let i=0;i<5;i++)g.chop();g.claimQuest('chop5');const value=g.state.resources.peaches;assert.throws(()=>g.claimQuest('chop5'),/已经领取/);assert.equal(g.state.resources.peaches,value);g.checkIn();assert.throws(()=>g.checkIn(),/已经领取/);});
test('locked skills and insufficient training leave state unchanged',()=>{const s=C.fresh(START);s.resources.gold=0;const g=fixture(s);assert.throws(()=>g.setSkill('thunder'),/境界不足/);assert.throws(()=>g.train('atk'),/灵石不足/);assert.equal(g.state.skill,'sword');assert.equal(g.state.training.atk,0);});
test('battle rewards and stage progression are issued once per battle',()=>{const g=fixture();for(let i=0;i<12;i++)g.chop(true);const battle=g.beginBattle('adventure');assert.ok(battle.result.win);assert.throws(()=>g.chop(),/正在战斗/);const result=g.finishBattle(battle.id);assert.ok(result.win);assert.equal(g.state.stage,2);const after=JSON.stringify(g.state);assert.throws(()=>g.finishBattle(battle.id),/已结束/);assert.equal(JSON.stringify(g.state),after);});
test('cancelled battles cannot award rewards',()=>{const g=fixture();const battle=g.beginBattle('adventure');g.cancelBattle();assert.throws(()=>g.finishBattle(battle.id));assert.equal(g.state.stage,1);assert.equal(g.state.counts.wins,0);});
test('tribulation charges its fee but consumes experience only after success',()=>{const g=fixture();assert.throws(()=>g.beginBattle('trial'),/修为不足/);for(let i=0;i<12;i++)g.chop(true);const gold=g.state.resources.gold,xp=g.state.xp,b=g.beginBattle('trial');assert.equal(g.state.resources.gold,gold-C.realmCost(0));assert.ok(b.result.win);g.finishBattle(b.id);assert.equal(g.state.realm,1);assert.equal(g.state.xp,xp-C.realmXp(0));});
test('a failed tribulation keeps experience and does not advance the realm',()=>{const g=fixture();g.state.xp=100;const b=g.beginBattle('trial');b.result.win=false;g.finishBattle(b.id);assert.equal(g.state.xp,100);assert.equal(g.state.realm,0);});
test('offline gain is capped at 12 hours and cannot be claimed twice',()=>{let now=START;const g=new C.Game(C.fresh(START),{now:()=>now,rng:rng()});now+=24*3600000;const result=g.tick();assert.equal(result.peaches,1440);assert.equal(g.state.resources.peaches,1560);assert.equal(g.tick(),null);});
test('passive generation preserves partial ticks and handles a backward clock',()=>{let now=START;const g=new C.Game(C.fresh(START),{now:()=>now});now+=31000;assert.equal(g.tick().peaches,1);now+=28000;assert.equal(g.tick(),null);now+=1000;assert.equal(g.tick().peaches,1);now=START;assert.equal(g.tick(),null);assert.equal(g.state.lastTick,START);});
test('daily reset uses Beijing midnight and keeps permanent missions',()=>{let now=Date.parse('2026-10-09T15:59:50Z');const g=new C.Game(C.fresh(now),{now:()=>now});g.checkIn();g.state.claimed.push('chop5');now+=20000;g.tick();assert.equal(g.state.daily.date,'2026-10-10');assert.equal(g.state.daily.checked,false);assert.ok(g.state.claimed.includes('chop5'));g.checkIn();assert.equal(g.state.checkIns,2);});
test('export and import retain equipment, companions and progression',()=>{const g=fixture();for(let i=0;i<15;i++)g.chop(true);g.summonPet();g.train('hp');const h=fixture(C.parseSave(g.serialize(),START));assert.deepEqual(h.state.equipment,g.state.equipment);assert.deepEqual(h.state.pets,g.state.pets);assert.deepEqual(h.state.training,g.state.training);assert.equal(h.state.counts.chops,15);});
test('invalid imports do not replace a current game',()=>{const g=fixture();g.chop();const before=JSON.stringify(g.state);assert.throws(()=>g.import('{broken'));assert.throws(()=>g.import({format:C.FORMAT,version:2,state:g.state}));assert.equal(JSON.stringify(g.state),before);});
test('import rejects resource strings and duplicate or inconsistent equipment',()=>{const g=fixture(),item=g.chop().item;const bad=JSON.parse(g.serialize());bad.state.resources.gold='Infinity';assert.throws(()=>C.parseSave(bad,START));bad.state.resources.gold=600;bad.state.bag.push({...item});assert.throws(()=>C.parseSave(bad,START),/重复/);bad.state.bag.pop();bad.state.equipment.robe={...item,slot:'weapon'};assert.throws(()=>C.parseSave(bad,START),/匹配/);});
test('import restores unique item numbering even when nextItem is stale',()=>{const g=fixture();for(let i=0;i<5;i++)g.chop();const data=JSON.parse(g.serialize());data.state.nextItem=1;const h=fixture(C.parseSave(data,START));assert.equal(h.chop().item.id,'item-6');});
test('summoning duplicates grants food; 20 misses guarantee a high-quality pet',()=>{const g=fixture();g.rng=()=>0;const food=g.state.resources.food;assert.ok(g.summonPet().duplicate);assert.ok(g.state.resources.food>food);g.state.resources.eggs=1;g.state.petPity=19;const result=g.summonPet();assert.equal(result.pet.id,'dragon');assert.equal(g.state.petPity,0);});
test('companion slots obey realm unlocks and star buffs apply to combat',()=>{const g=fixture();g.state.spirits.push({id:'flame',star:1});assert.throws(()=>g.toggleSpirit('flame'),/位置已满/);g.state.realm=3;const before=g.stats().atk;g.toggleSpirit('flame');assert.ok(g.stats().atk>before);assert.equal(g.state.activeSpirits.length,2);});
test('combat traits produce actual combo, lifesteal and dodge events',()=>{const a={atk:45,hp:150,def:0,speed:20,combo:1,crit:0,counter:0,lifesteal:.2,dodge:0,stun:0},b={atk:20,hp:250,def:0,speed:10,combo:0,crit:0,counter:0,lifesteal:0,dodge:0,stun:0};const result=C.simulateBattle(a,b,{rng:()=>.5});assert.ok(result.events.some(e=>e.type==='combo'));assert.ok(result.events.some(e=>e.type==='heal'&&e.amount>0));const dodge=C.simulateBattle({...a,dodge:1},{...b,dodge:1},{rng:()=>.5});assert.ok(dodge.timeout);assert.equal(dodge.rounds,30);assert.ok(dodge.events.every(e=>e.type==='dodge'));});
test('a counter attack that kills the attacker stops further attacks',()=>{const a={atk:10,hp:5,def:0,speed:20,combo:1,crit:0,counter:0,lifesteal:0,dodge:0,stun:0},b={atk:100,hp:200,def:0,speed:10,combo:0,crit:0,counter:1,lifesteal:0,dodge:0,stun:0};const result=C.simulateBattle(a,b,{rng:()=>.5});assert.equal(result.events.length,2);assert.equal(result.playerHp,0);assert.equal(result.win,false);});
